config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#index'
  resources :books
  resources :user_books, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :user_books, dependent: :destroy
  validates :title, presence: true
  validates :author, presence: true
  validates :total_books, presence: true
  validates :cost_day, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_books
  validates :username, uniqueness: true, presence: true
  validates :balance, presence: true
end

app/models/user_book.rb
class UserBook < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :balance])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :balance])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
  end

  def update
    @book.update(book_params)
  end

  def find_book
    @book = Book.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :total_books, :checked_books, :cost_day)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
  before_action :find_user_book, only: [:edit, :update, :destroy]
  def new
    @user_book = UserBook.new
  end

  def create
    @user_book = UserBook.create(user_book_params)
    @user_book.user = current_user
    @user_book.checkout_date = DateTime.current.to_date
    @user_book.save
    @book = @user_book.book
    @book.total_books -= 1
    @book.save
  #  book = Book.find(params[:book_id])
  #  @user_book.book = book
   # @user_book.book.total_books = @user_book.book.total_books - 1
    redirect_to root_path
  end

  def destroy
    @user = @user_book.user
    @book = @user_book.book
    @user.balance -= @book.cost_day #* (Date.today - @user_book.checkout_date).to_i
    @user.save
    @book.total_books += 1
    @book.save
    @user_book.destroy
    redirect_to root_path
  end

  private

  def find_user_book
    @user_book = UserBook.find(params[:id])
  end

  def user_book_params
    params.require(:user_book).permit(:book_id, :user_id, :checkout_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize @user
    @user_book = UserBook.new
    authorize @user_book
    @user_book = current_user.user_books
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
 <% if current_user.balance > 0 %>
 <td><%= link_to "Borrow", new_user_book_path, :action => 'go' %><td>
  <% else %>
 <td><%= link_to "Add to Balance", edit_user_registration_path, :action => 'go' %><td>
  <% end%>
 <table style="width:100%">
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Author</th>
    <th>Books Remaining</th>
    <th>Cost</th>
    <th>Checked out by you</th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td><%= book.id %></td>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.total_books %></td>
    <td><%= book.cost_day %></td>
    <% book.user_books.each do |user_book| %>
      <% if user_book.user_id == current_user.id %>
        <td>Y</td>
        <% if current_user.balance >= book.cost_day %>
          <td><%= link_to "Return", user_book_path(user_book.id), method: :delete,class: "nav-link" %><td>
            <% else %>
            <td>Please add to balance before returning</td>
        <% end %>
      <% end %>
    <% end %>
  </tr>
  <% end %>
</table>

<p>  User Balance: $<%= current_user.balance %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>

  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <p class="nav-link">User Balance: $<%= current_user.balance %></p>
        </li>
        <li class="nav-item active">
          <%= link_to "Book List", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Add to Balance", edit_user_registration_path, :action => 'go', class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/user_books/_form.html.erb
<%= simple_form_for(user_book) do |f| %>
    <%= f.input :book_id, label: "Book ID", required: true %><br>
    <%= f.button :submit, "Borrow", class: "form-create" %>
<% end %>

app/views/user_books/new.html.erb
<%= render "form", user_book: @user_book %>